- hosts: all
  become: true
  pre_tasks:
   - name: Disable SELinux
     ansible.posix.selinux:
       state: disabled
  roles:
    - role: amygos.traefik
      vars:
        traefik_static_configuration:
          entryPoints:
            https:
              address: :443
            metrics:
              address: :8082
          providers:
            file:
              directory: /etc/traefik/conf.d
          accessLog:
            format: json
          metrics:
            prometheus:
              entryPoint: metrics
              addEntryPointsLabels: true
              addServicesLabels: true
          ping:
            manualRouting: true
    - role: fpp
