http:
  routers:
    ping-https:
      entryPoints:
      - https
      rule: Host(`fpp.gs.nethserver.net`) && Path(`/ping`)
      middlewares:
      - my-auth
      service: ping@internal
      tls:
        certResolver: letsencrypt
    register-nethesis:
      entryPoints:
        - https
      middlewares:
        - strip-brand
      rule: PathPrefix(`/nethesis/register`)
      service: fpp-nethesis
      tls: {}
    register-dev:
      entryPoints:
        - https
      middlewares:
        - strip-brand
      rule: PathPrefix(`/dev/register`)
      service: fpp-dev
      tls: {}
    send-push-nethesis:
      entryPoints:
        - https
      middlewares:
        - my-auth
        - remove-auth-header
        - strip-brand
      rule: PathPrefix(`/nethesis/`)
      service: fpp-nethesis
      tls: {}
    send-push-dev:
      entryPoints:
        - https
      middlewares:
        - my-auth
        - remove-auth-header
        - strip-brand
      rule: PathPrefix(`/dev/`)
      service: fpp-dev
      tls: {}
  middlewares:
    my-auth:
      forwardAuth:
        address: 'https://my.nethesis.it/auth'
    remove-auth-header:
      headers:
        customRequestHeaders:
          Authorization: ''
    strip-brand:
      stripPrefix:
        prefixes:
          - "/nethesis"
          - "/dev"
  services:
    fpp-nethesis:
      loadBalancer:
        passHostHeader: false
        servers:
          - url: 'http://localhost:9191'
    fpp-dev:
      loadBalancer:
        passHostHeader: false
        servers:
          - url: 'http://localhost:9292'

