{
 "title": "FPP (what the Fuck Push Proxy)",
 "description": "Push Proxy and Golang process statistics",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "brand",
    "label": "Instance brand",
    "query": {
     "query": "label_values(fpp_total_send_count, brand)"
    }
   }
  ]
 },
 "panels": [
  { "title": "DPP device stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total devices",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fpp_registered_apn_devices{brand=~\"^($brand)$\"} + fpp_registered_firebase_devices{brand=~\"^($brand)$\"}"
    }
   ]
  },
  {
   "title": "Registered devices",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fpp_registered_firebase_devices{brand=~\"^($brand)$\"}",
     "legendFormat": "Firebase"
    },
    {
     "expr": "fpp_registered_apn_devices{brand=~\"^($brand)$\"}",
     "legendFormat": "Apple"
    }
   ]
  },
  {
   "title": "Devices by type",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 10, "y": 1 },
   "targets": [
    {
     "expr": "fpp_registered_apn_devices{brand=~\"^($brand)$\"}",
     "legendFormat": "Apple"
    },
    {
     "expr": "fpp_registered_firebase_devices{brand=~\"^($brand)$\"}",
     "legendFormat": "Firebase"
    },
    {
     "expr": "fpp_registered_firebase_devices{brand=~\"^($brand)$\"} + fpp_registered_apn_devices{brand=~\"^($brand)$\"}",
     "legendFormat": "Total"
    }
   ]
  },
  { "title": "FPP send stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Total sent notifications",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fpp_total_send_count{brand=\"$brand\"}"
    }
   ]
  },
  {
   "title": "Sent in last 5 minutes",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(fpp_total_send_count{brand=~\"^($brand)$\"}[5m])"
    }
   ]
  },
  {
   "title": "Sent by type",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 5, "x": 10, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(fpp_apn_success_count{brand=~\"^($brand)$\"}[$__rate_interval])",
     "legendFormat": "Apple"
    },
    {
     "expr": "rate(fpp_firebase_success_count{brand=~\"^($brand)$\"}[$__rate_interval])",
     "legendFormat": "Firebase"
    }
   ]
  },
  {
   "title": "Successfull send",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "rate(fpp_apn_success_count{brand=~\"^($brand)$\"}[$__rate_interval])",
     "legendFormat": "Apple"
    },
    {
     "expr": "rate(fpp_firebase_success_count{brand=~\"^($brand)$\"}[$__rate_interval])",
     "legendFormat": "Firebase"
    },
    {
     "expr": "rate(fpp_firebase_success_count{brand=~\"^($brand)$\"}[$__rate_interval]) + rate(fpp_apn_success_count{brand=~\"^($brand)$\"}[$__rate_interval])",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Errored send",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "rate(fpp_apn_error_count{brand=~\"^($brand)$\"}[$__rate_interval])",
     "legendFormat": "Apple"
    },
    {
     "expr": "rate(fpp_firebase_error_count{brand=~\"^($brand)$\"}[$__rate_interval])",
     "legendFormat": "Firebase"
    },
    {
     "expr": "rate(fpp_firebase_error_count{brand=~\"^($brand)$\"}[$__rate_interval]) + rate(fpp_apn_error_count{brand=~\"^($brand)$\"}[$__rate_interval])",
     "legendFormat": "Total"
    }
   ]
  },
  { "title": "GO process stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Process memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{brand=~\"^($brand)$\",job=\"fpp\"}",
     "legendFormat": "Resident"
    },
    {
     "expr": "process_virtual_memory_bytes{brand=~\"^($brand)$\",job=\"fpp\"}",
     "legendFormat": "Virtual"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{brand=~\"^$brand$\"}[$__rate_interval])",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "title": "Open File Descriptors (FD)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "process_open_fds{brand=~\"^($brand)$\",job=\"fpp\"}",
     "legendFormat": "Number of FD"
    }
   ]
  }
 ]
}