{
 "title": "FPP (what the Fuck Push Proxy)",
 "description": "Push Proxy and Golang process statistics",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": "label_values(go_memstats_alloc_bytes, namespace)"
   },
   {
    "name": "pod",
    "query": "label_values(process_resident_memory_bytes, pod)"
   },
   { "name": "interval", "query": "1m,5m,10m,30m,1h" }
  ]
 },
 "panels": [
  {
   "title": "DPP device stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true
  },
  {
   "title": "Total devices",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fpp_registered_apn_devices + fpp_registered_firebase_devices"
    }
   ]
  },
  {
   "title": "Registered devices",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "fpp_registered_apn_devices", "legendFormat": "Apple" },
    {
     "expr": "fpp_registered_firebase_devices",
     "legendFormat": "Firebase"
    }
   ]
  },
  {
   "title": "Devices by type",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 10, "y": 1 },
   "targets": [
    { "expr": "fpp_registered_apn_devices", "legendFormat": "Apple" },
    {
     "expr": "fpp_registered_firebase_devices",
     "legendFormat": "Firebase"
    },
    {
     "expr": "fpp_registered_firebase_devices + fpp_registered_apn_devices",
     "legendFormat": "Total"
    }
   ]
  },
  { "title": "FPP send stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Total sent notifications",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "fpp_total_send_count" }
   ]
  },
  {
   "title": "Sent in last 5 minutes",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "rate(fpp_total_send_count[5m])" }
   ]
  },
  {
   "title": "Sent by type",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 5, "x": 10, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(fpp_apn_success_count[$__rate_interval])",
     "legendFormat": "Apple"
    },
    {
     "expr": "rate(fpp_firebase_success_count[$__rate_interval])",
     "legendFormat": "Firebase"
    }
   ]
  },
  {
   "title": "Successfull send",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "rate(fpp_apn_success_count[$__rate_interval])",
     "legendFormat": "Apple"
    },
    {
     "expr": "rate(fpp_firebase_success_count[$__rate_interval])",
     "legendFormat": "Firebase"
    },
    {
     "expr": "rate(fpp_firebase_success_count[$__rate_interval]) + rate(fpp_apn_success_count[$__rate_interval])",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Errored send",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "rate(fpp_apn_error_count[$__rate_interval])",
     "legendFormat": "Apple"
    },
    {
     "expr": "rate(fpp_firebase_error_count[$__rate_interval])",
     "legendFormat": "Firebase"
    },
    {
     "expr": "rate(fpp_firebase_error_count[$__rate_interval]) + rate(fpp_apn_error_count[$__rate_interval])",
     "legendFormat": "Total"
    }
   ]
  },
  { "title": "GO process stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Process memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{namespace=~\"^($namespace)$\",pod=~\"^($pod)$\"}",
     "legendFormat": "{{pod}} - resident"
    },
    {
     "expr": "process_virtual_memory_bytes{namespace=~\"^($namespace)$\",pod=~\"^($pod)$\"}",
     "legendFormat": "{{pod}} - virtual"
    }
   ]
  },
  {
   "title": "Open FDs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "process_open_fds{namespace=~\"^($namespace)$\",pod=~\"^($pod)$\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}