---
- name: Download fpp
  ansible.builtin.get_url:
    url: "{{ fpp_url }}/releases/download/{{ fpp_version }}/fpp_{{ fpp_version }}_linux_amd64.tar.gz"
    dest: /tmp
  register: _download_archive
  until: _download_archive is succeeded
  retries: 5
  delay: 2
  check_mode: false

- name: Install fpp
  unarchive:
    src: "/tmp/fpp_{{ fpp_version }}_linux_amd64.tar.gz"
    dest: /usr/bin
    remote_src: yes
    mode: 0755
    owner: root
    group: root
    exclude:
      - CHANGELOG.md
      - LICENSE.md

- name: Add the user 'fpp'
  ansible.builtin.user:
    name: fpp
    create_home: false

- name: Create fpp working directory
  ansible.builtin.file:
    path: /var/local/fpp/
    state: directory
    recurse: yes

- name: Create fpp badger dbs directory
  ansible.builtin.file:
    path: /var/local/fpp/dbs
    state: directory
    recurse: yes
    owner: fpp
    group: fpp

- name: Create fpp brand directory
  ansible.builtin.file:
    path: /var/local/fpp/{{ brand_name }}
    state: directory
    recurse: yes

- name: Copy brand Google credentials file
  ansible.builtin.copy:
    dest: "/var/local/fpp/{{ brand_name }}/credentials.json"
    src: "{{ brand_google_credentials_file }}"

- name: Copy brand Apple credentials file
  ansible.builtin.copy:
    dest: "/var/local/fpp/{{ brand_name }}/credentials.p8"
    src: "{{ brand_apple_credentials_file }}"

- name: Generate brand configuration file
  ansible.builtin.copy:
    content: |
      LISTEN=127.0.0.1:{{ brand_http_port }}
      APPLE_TEAM_ID={{ brand_apple_team_id }}
      APPLE_KEY_ID={{ brand_apple_key_id }}
      APPLE_TOPIC={{ brand_apple_topic }}
      APPLE_ENVIRONMENT={{ brand_apple_environment }}
      INSTANCE_TOKEN={{ brand_instance_token }}
    dest: "/var/local/fpp/{{ brand_name }}/env"

- name: Copy systemd unit file
  ansible.builtin.copy:
    dest: /usr/lib/systemd/system/
    src: fpp@.service

- name: Systemd configuration
  ansible.builtin.systemd:
    name: "fpp@{{ brand_name }}"
    daemon_reload: true
    enabled: true
    state: started

- name: Copy traefik /ping configuration
  ansible.builtin.copy:
    dest: /etc/traefik/conf.d/ping.yml
    src: traefik_ping.yml

- name: Generate traefik middlewares configuration
  ansible.builtin.template:
    src: traefik_middlewares.yml.j2
    dest: /etc/traefik/conf.d/traefik_middlewares.yml

- name: Generate traefik brand configuration
  ansible.builtin.template:
    src: traefik_brand.yml.j2
    dest: /etc/traefik/conf.d/{{ brand_name }}.yml
